{"uuid": "f463d09b-f146-4fd4-92e8-6ac3e3c5fd8d", "children": ["4c7d2bae-f686-4a98-a7b2-f4d181de2078"], "befores": [{"name": "login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument\n  (Session info: chrome=114.0.5735.199)\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x00A4A813+48355]\n\t(No symbol) [0x009DC4B1]\n\t(No symbol) [0x008E5220]\n\t(No symbol) [0x008D88E2]\n\t(No symbol) [0x008D7138]\n\t(No symbol) [0x008D7688]\n\t(No symbol) [0x008E6B52]\n\t(No symbol) [0x0093CF01]\n\t(No symbol) [0x0092A73C]\n\t(No symbol) [0x0093C922]\n\t(No symbol) [0x0092A536]\n\t(No symbol) [0x009082DC]\n\t(No symbol) [0x009093DD]\n\tGetHandleVerifier [0x00CAAABD+2539405]\n\tGetHandleVerifier [0x00CEA78F+2800735]\n\tGetHandleVerifier [0x00CE456C+2775612]\n\tGetHandleVerifier [0x00AD51E0+616112]\n\t(No symbol) [0x009E5F8C]\n\t(No symbol) [0x009E2328]\n\t(No symbol) [0x009E240B]\n\t(No symbol) [0x009D4FF7]\n\tBaseThreadInitThunk [0x76AD7D59+25]\n\tRtlInitializeExceptionChain [0x77BAB79B+107]\n\tRtlClearBits [0x77BAB71F+191]\n\n", "trace": "  File \"C:\\Users\\skmee\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\skmee\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1128, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\skmee\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 907, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\skmee\\PycharmProjects\\udemy_autotests_web\\tests\\conftest.py\", line 22, in login\n    app.user_log_in.open() \\\n    ^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\skmee\\PycharmProjects\\udemy_autotests_web\\udemy_autotests_web\\model\\pages\\user_log_in_page.py\", line 6, in open\n    browser.open('/users/sign_in')\n  File \"C:\\Users\\skmee\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selene\\core\\entity.py\", line 1154, in open\n    self.config._executor.get_url(relative_or_absolute_url)\n  File \"C:\\Users\\skmee\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selene\\core\\configuration.py\", line 303, in get_url\n    self.config._driver_get_url_strategy(self.config)(url)\n  File \"C:\\Users\\skmee\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selene\\core\\configuration.py\", line 255, in get\n    driver.get(url)\n  File \"C:\\Users\\skmee\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 449, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\skmee\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\skmee\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1689501824839, "stop": 1689501830719}], "start": 1689501824839, "stop": 1689501831702}