WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A6EB9C5F50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/7c7101b44aff76a7eedb44c7bd2ac210
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A6EB3ED5D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/7c7101b44aff76a7eedb44c7bd2ac210
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A6EB9C9110>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/7c7101b44aff76a7eedb44c7bd2ac210