{"name": "test_with_invalid_email", "status": "broken", "statusDetails": {"message": "AttributeError: module 'urllib.request' has no attribute 'config'", "trace": "@pytest.fixture(scope=\"function\", autouse=True)\n    def setup_browser():\n>       browser_name = request.config.getoption('browser_name')\nE       AttributeError: module 'urllib.request' has no attribute 'config'\n\ntests\\conftest.py:31: AttributeError"}, "start": 1689778385920, "stop": 1689778385920, "uuid": "c6ca8fa9-c533-4b47-86d9-f1b1851347a5", "historyId": "267ad1994ab712361545180c4a21d3b1", "testCaseId": "267ad1994ab712361545180c4a21d3b1", "fullName": "tests.test_signup#test_with_invalid_email", "labels": [{"name": "tag", "value": "web"}, {"name": "feature", "value": "Signing up with invalid credentials"}, {"name": "story", "value": "Verify that an appropriate error message is displayed and still on same url"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_signup"}, {"name": "host", "value": "LAPTOP-OFQSKCIR"}, {"name": "thread", "value": "16652-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_signup"}]}