{"name": "test_bookmark_job", "status": "broken", "statusDetails": {"message": "ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115.0.5790", "trace": "@pytest.fixture(scope=\"session\")\n    def login():\n>       app.user_log_in.open() \\\n            .fill_email(user.email) \\\n            .fill_password(user.password) \\\n            .login_button()\n\ntests\\conftest.py:65: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nworkingnomads_autotests_web\\model\\pages\\user_log_in_page.py:6: in open\n    browser.open('/users/sign_in')\n..\\..\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\workingnomads-autotest-web-JpeIW-ZQ-py3.11\\Lib\\site-packages\\selene\\support\\shared\\browser.py:83: in open\n    self.config.get_or_create_driver().get(url)\n..\\..\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\workingnomads-autotest-web-JpeIW-ZQ-py3.11\\Lib\\site-packages\\selene\\support\\shared\\config.py:301: in get_or_create_driver\n    return self._source.get_or_create()\n..\\..\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\workingnomads-autotest-web-JpeIW-ZQ-py3.11\\Lib\\site-packages\\selene\\support\\shared\\config.py:135: in get_or_create\n    return self.create()\n..\\..\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\workingnomads-autotest-web-JpeIW-ZQ-py3.11\\Lib\\site-packages\\selene\\support\\shared\\config.py:116: in create\n    self._stored = self._set_driver()\n..\\..\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\workingnomads-autotest-web-JpeIW-ZQ-py3.11\\Lib\\site-packages\\selene\\support\\shared\\config.py:203: in <lambda>\n    lambda: self._set_drivers_from_webdriver_manager()\n..\\..\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\workingnomads-autotest-web-JpeIW-ZQ-py3.11\\Lib\\site-packages\\selene\\support\\shared\\config.py:277: in _set_drivers_from_webdriver_manager\n    return {\n..\\..\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\workingnomads-autotest-web-JpeIW-ZQ-py3.11\\Lib\\site-packages\\selene\\support\\shared\\config.py:256: in get_chrome\n    ).install()\n..\\..\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\workingnomads-autotest-web-JpeIW-ZQ-py3.11\\Lib\\site-packages\\webdriver_manager\\chrome.py:39: in install\n    driver_path = self._get_driver_path(self.driver)\n..\\..\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\workingnomads-autotest-web-JpeIW-ZQ-py3.11\\Lib\\site-packages\\webdriver_manager\\core\\manager.py:30: in _get_driver_path\n    file = self._download_manager.download_file(driver.get_driver_download_url())\n..\\..\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\workingnomads-autotest-web-JpeIW-ZQ-py3.11\\Lib\\site-packages\\webdriver_manager\\drivers\\chrome.py:40: in get_driver_download_url\n    driver_version_to_download = self.get_driver_version_to_download()\n..\\..\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\workingnomads-autotest-web-JpeIW-ZQ-py3.11\\Lib\\site-packages\\webdriver_manager\\core\\driver.py:51: in get_driver_version_to_download\n    self._driver_to_download_version = self._version if self._version not in (None, \"latest\") else self.get_latest_release_version()\n..\\..\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\workingnomads-autotest-web-JpeIW-ZQ-py3.11\\Lib\\site-packages\\webdriver_manager\\drivers\\chrome.py:62: in get_latest_release_version\n    resp = self._http_client.get(url=latest_release_url)\n..\\..\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\workingnomads-autotest-web-JpeIW-ZQ-py3.11\\Lib\\site-packages\\webdriver_manager\\core\\http.py:37: in get\n    self.validate_response(resp)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nresp = <Response [404]>\n\n    @staticmethod\n    def validate_response(resp: requests.Response):\n        status_code = resp.status_code\n        if status_code == 404:\n>           raise ValueError(f\"There is no such driver by url {resp.url}\")\nE           ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115.0.5790\n\n..\\..\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\workingnomads-autotest-web-JpeIW-ZQ-py3.11\\Lib\\site-packages\\webdriver_manager\\core\\http.py:16: ValueError"}, "start": 1689778385799, "stop": 1689778385799, "uuid": "d440ff0f-97da-467e-9ade-b0603d555459", "historyId": "26389278e94a97283df77bb20091559b", "testCaseId": "26389278e94a97283df77bb20091559b", "fullName": "tests.test_job_bookmarks#test_bookmark_job", "labels": [{"name": "feature", "value": "Bookmark"}, {"name": "story", "value": "First filter out jobs and add one of them to bookmarks"}, {"name": "tag", "value": "web"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_job_bookmarks"}, {"name": "host", "value": "LAPTOP-OFQSKCIR"}, {"name": "thread", "value": "16652-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_job_bookmarks"}]}